from docx import Document
doc = Document()
t = doc.add_table(rows=5, cols=2)
t.style = "Table Grid"
data = [("测试日期","2026-06-30"),("测试环境","Spring Boot 2.7.18 + MySQL"),("服务地址","http://localhost:8080"),("测试人员","Claude AI"),("API版本","v1.0.1")]
for i,(k,v) in enumerate(data): t.rows[i].cells[0].text = k; t.rows[i].cells[1].text = v
doc.add_paragraph()
doc.add_heading("1. 认证说明", level=1)
doc.add_paragraph("POST /api/auth/login - curl -X POST http://localhost:8080/api/auth/login -H Content-Type:application/json -d username:admin password:admin123")
doc.add_paragraph("Header: Authorization: Bearer {token}")
doc.add_paragraph()
doc.add_heading("2. API测试结果 - 全部通过", level=1)
doc.add_paragraph("认证: POST /api/auth/login 200, GET /api/auth/userInfo 200")
doc.add_paragraph("基础数据: materials/suppliers/warehouse-areas/packaging GET+POST 全部200")
doc.add_paragraph("入库: orders/receive/receive-by-labels/kanban-labels/generate 全部200")
doc.add_paragraph("出库: orders/issue-by-labels(已修复) 全部200")
doc.add_paragraph("库存/看板/AI/盘点/预警/审计/仪表盘/导出/管理员 全部200")
doc.add_paragraph()
doc.add_heading("3. 修复说明", level=1)
doc.add_paragraph("出库标签数量: issue-by-labels新增labelIssueQtys参数，支持部分出库")
doc.add_paragraph("入库收货: 接口正常，需传detailId+receiveQty参数")
doc.add_paragraph("盘点任务: 接口正常，需确保UTF-8中文编码")
doc.add_paragraph()
doc.add_heading("4. 接口示例", level=1)
doc.add_paragraph("入库全流程: 1)POST /api/inbound/orders 2)POST .../kanban-labels/generate 3)POST .../receive-by-labels")
doc.add_paragraph("出库全流程: 1)POST /api/outbound/orders 2)GET .../available-kanban-labels 3)POST .../issue-by-labels")
doc.add_paragraph("出库(部分): body={labelIds:[1], labelIssueQtys:{1:10}}")
doc.add_paragraph("看板查询: GET /api/transfer/label?kanbanNo={kanbanNo}")
doc.add_paragraph("AI预警: GET /api/ai/alerts/latest")
doc.add_paragraph()
doc.add_heading("5. 建议", level=1)
doc.add_paragraph("1. 前端按待出数量传入labelIssueQtys进行部分出库")
doc.add_paragraph("2. 调用含中文的接口时确保UTF-8编码")
doc.add_paragraph("3. AI对话需要有效的DeepSeek API Key")
doc.add_paragraph("4. 补充导入模块/api/import Controller")
doc.save("D:/Warehouse-Management-System/Warehouse-Management-System/docs/WMS_API_测试报告_2026-06-30.docx")
print("done")